### ISSUE TITLE
关于如何创建新menu并关联页面

### ISSUE THREAD

**Issue by safly** [goodspb/laravel-user-center#1]
您好 GoodSpb！
最近在研究 laravel，您的 laravel-user-center 真的是让我正在做的一个项目方便了很多。
我想通过您的 laravel-user-center 入门 laravel，研究了半天没研究出怎么创建新menu并关联页面，我在 ./config/menus.php 里写了一个菜单但卡在怎么关联一个php程序了，在 laravel 官网看好像要 php artisan 什么东西，原谅我没研究明白...
我想请教一下怎么创建一个menu并关联页面，例如在管理员页面和普通用户页面增加一个菜单并显示当前用户的用户名。
十分感谢！

**Comment by safly** [comment]
已解决，豁然开朗，十分感谢！

**Comment by goodspb** [comment]
加油。
